```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=TRUE, comment='', results='markup')
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here

```

# Problem
You want to build a `SpatialPoints` object, inspect their structure.

# Solution
Use a `matrix` of coordinates and a `CRS` object as arguments for the `SpatialPoints` function:
```{r readOGR}
library(sp)
# Draw a random sample of points.
pts <- matrix(c(sample(3:10, 10, r = T),
                sample(70:100, 10, r = T)),
              nc = 2)
crs <- CRS(projargs = as.character(NA))
sp.pt <- SpatialPoints(pts, crs)
str(sp.pt, 2)
summary(sp.pt)

# bbox is created from pts.
bbox(sp.pt)

# Access the first 3 coordinates
coordinates(sp.pt[1:3, ])
```

# Discussion
In addition to `@` and `slot`, the `coordinates` function can be used to access the `coords` slot.

# See also



















































